# Lab 01: Introduction to PyTorch  

In [1]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [4]:
A=torch.rand(10,2)
print(A)

tensor([[0.0861, 0.0605],
        [0.6779, 0.9222],
        [0.9551, 0.4396],
        [0.6454, 0.2751],
        [0.8473, 0.8037],
        [0.7962, 0.2018],
        [0.8937, 0.0156],
        [0.0956, 0.0329],
        [0.4460, 0.0368],
        [0.8121, 0.1415]])


### Construct a 10 x 2 matrix filled with zeros

In [5]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [6]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.9989, 0.8228],
         [0.0127, 0.6292]],

        [[0.6571, 0.3450],
         [0.0552, 0.3681]],

        [[0.0576, 0.0366],
         [0.5104, 0.4821]],

        [[0.4077, 0.4662],
         [0.9650, 0.6641]],

        [[0.4233, 0.7930],
         [0.7726, 0.3918]]])


In [7]:
B.size()

torch.Size([5, 2, 2])

In [8]:
B.dim()

3

In [9]:
B.type()

'torch.FloatTensor'

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [10]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.1874, 0.8582],
         [0.6521, 0.7820]],

        [[0.9411, 0.8457],
         [0.6555, 0.5234]],

        [[0.6926, 0.6058],
         [0.9695, 0.6842]]])


In [11]:
print(  A.dim()   )

3


In [12]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [13]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [14]:
B=torch.rand(3,5)
print(B)

tensor([[0.3832, 0.9663, 0.1671, 0.2752, 0.4608],
        [0.8758, 0.6267, 0.4151, 0.6652, 0.7178],
        [0.4919, 0.0383, 0.4818, 0.4174, 0.7463]])


In [15]:
print( B.dim()  )

2


In [16]:
print( B.size()  )

torch.Size([3, 5])


In [17]:
print( B.size(0) )

3


In [18]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [19]:
x=torch.rand(7)
print(x)

tensor([0.4580, 0.9118, 0.3229, 0.8990, 0.3899, 0.0010, 0.5181])


In [20]:
print( x.dim() )

1


In [21]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [22]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.2432, 0.6679],
        [0.5275, 0.3159]])

tensor([[0.8190, 0.6622],
        [0.6144, 0.2628]])

tensor([[1.6380, 1.3243],
        [1.2287, 0.5256]])

tensor([[1.6380, 1.3243],
        [1.2287, 0.5256]])

tensor([[0.1992, 0.4423],
        [0.3241, 0.0830]])


### Floats versus integers

In [23]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [24]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [25]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [26]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [27]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [28]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([0, 4, 7, 9, 8, 5, 3, 1, 6, 2])
torch.LongTensor


In [29]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [30]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [32]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [33]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [34]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [35]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [36]:
print( y[0] )

tensor([0, 1])


In [37]:
print( y[1] )

tensor([2, 3])


In [38]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [39]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [40]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [41]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [42]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [43]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [44]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [45]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [46]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [47]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [48]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [49]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
